{
    "openapi": "3.0.3",
    "info": {
        "title": "DjangoAPI",
        "version": "2.0.0",
        "description": "User and Blog API for Django project"
    },
    "paths": {
        "/api/blogs/": {
            "get": {
                "operationId": "Get_Blogs",
                "tags": [
                    "blogs"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Blog"
                                    }
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": [
                                            {
                                                "id": 1,
                                                "user": 1,
                                                "title": "Doloremque et et.",
                                                "content": "Discuss than some debate this. Entire him certain single west rock......",
                                                "created_at": "2021-06-11"
                                            }
                                        ],
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "post": {
                "operationId": "Create_Blog",
                "tags": [
                    "blogs"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/BlogRequest"
                            },
                            "examples": {
                                "ExampleResponse": {
                                    "value": {
                                        "id": 1,
                                        "user": 1,
                                        "title": "Doloremque et et.",
                                        "content": "Discuss than some debate this. Entire him certain single west rock......",
                                        "created_at": "2021-06-11"
                                    },
                                    "summary": "Detailed example"
                                }
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/BlogRequest"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/BlogRequest"
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Blog"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "user": 1,
                                            "title": "Doloremque et et.",
                                            "content": "Discuss than some debate this. Entire him certain single west rock......",
                                            "created_at": "2021-06-11"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/api/blogs/{id}/": {
            "get": {
                "operationId": "Get_Blog",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this blog.",
                        "required": true
                    }
                ],
                "tags": [
                    "blogs"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Blog"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "user": 1,
                                            "title": "Doloremque et et.",
                                            "content": "Discuss than some debate this. Entire him certain single west rock......",
                                            "created_at": "2021-06-11"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "put": {
                "operationId": "Update_Blog",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this blog.",
                        "required": true
                    }
                ],
                "tags": [
                    "blogs"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/BlogRequest"
                            },
                            "examples": {
                                "ExampleResponse": {
                                    "value": {
                                        "id": 1,
                                        "user": 1,
                                        "title": "Doloremque et et.",
                                        "content": "Discuss than some debate this. Entire him certain single west rock......",
                                        "created_at": "2021-06-11"
                                    },
                                    "summary": "Detailed example"
                                }
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/BlogRequest"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/BlogRequest"
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Blog"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "user": 1,
                                            "title": "Doloremque et et.",
                                            "content": "Discuss than some debate this. Entire him certain single west rock......",
                                            "created_at": "2021-06-11"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "patch": {
                "operationId": "Partial_Update_Blog",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this blog.",
                        "required": true
                    }
                ],
                "tags": [
                    "blogs"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchedBlogRequest"
                            },
                            "examples": {
                                "ExampleResponse": {
                                    "value": {
                                        "id": 1,
                                        "user": 1,
                                        "title": "Doloremque et et.",
                                        "content": "Discuss than some debate this. Entire him certain single west rock......",
                                        "created_at": "2021-06-11"
                                    },
                                    "summary": "Detailed example"
                                }
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchedBlogRequest"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchedBlogRequest"
                            }
                        }
                    }
                },
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Blog"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "user": 1,
                                            "title": "Doloremque et et.",
                                            "content": "Discuss than some debate this. Entire him certain single west rock......",
                                            "created_at": "2021-06-11"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "delete": {
                "operationId": "Delete_Blog",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this blog.",
                        "required": true
                    }
                ],
                "tags": [
                    "blogs"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No response body"
                    }
                }
            }
        },
        "/api/health/": {
            "get": {
                "operationId": "Get_Health",
                "parameters": [
                    {
                        "in": "query",
                        "name": "db",
                        "schema": {
                            "type": "string",
                            "enum": [
                                "1"
                            ]
                        },
                        "description": "`1` also runs `SELECT 1` against the database"
                    }
                ],
                "tags": [
                    "health"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Health"
                                }
                            }
                        },
                        "description": ""
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Health"
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/api/schema/": {
            "get": {
                "operationId": "schema_retrieve",
                "description": "OpenApi3 schema for this API. Format can be selected via content negotiation.\n\n- YAML: application/vnd.oai.openapi\n- JSON: application/vnd.oai.openapi+json",
                "parameters": [
                    {
                        "in": "query",
                        "name": "format",
                        "schema": {
                            "type": "string",
                            "enum": [
                                "json",
                                "yaml"
                            ]
                        }
                    },
                    {
                        "in": "query",
                        "name": "lang",
                        "schema": {
                            "type": "string",
                            "enum": [
                                "af",
                                "ar",
                                "ar-dz",
                                "ast",
                                "az",
                                "be",
                                "bg",
                                "bn",
                                "br",
                                "bs",
                                "ca",
                                "ckb",
                                "cs",
                                "cy",
                                "da",
                                "de",
                                "dsb",
                                "el",
                                "en",
                                "en-au",
                                "en-gb",
                                "eo",
                                "es",
                                "es-ar",
                                "es-co",
                                "es-mx",
                                "es-ni",
                                "es-ve",
                                "et",
                                "eu",
                                "fa",
                                "fi",
                                "fr",
                                "fy",
                                "ga",
                                "gd",
                                "gl",
                                "he",
                                "hi",
                                "hr",
                                "hsb",
                                "hu",
                                "hy",
                                "ia",
                                "id",
                                "ig",
                                "io",
                                "is",
                                "it",
                                "ja",
                                "ka",
                                "kab",
                                "kk",
                                "km",
                                "kn",
                                "ko",
                                "ky",
                                "lb",
                                "lt",
                                "lv",
                                "mk",
                                "ml",
                                "mn",
                                "mr",
                                "ms",
                                "my",
                                "nb",
                                "ne",
                                "nl",
                                "nn",
                                "os",
                                "pa",
                                "pl",
                                "pt",
                                "pt-br",
                                "ro",
                                "ru",
                                "sk",
                                "sl",
                                "sq",
                                "sr",
                                "sr-latn",
                                "sv",
                                "sw",
                                "ta",
                                "te",
                                "tg",
                                "th",
                                "tk",
                                "tr",
                                "tt",
                                "udm",
                                "ug",
                                "uk",
                                "ur",
                                "uz",
                                "vi",
                                "zh-hans",
                                "zh-hant"
                            ]
                        }
                    }
                ],
                "tags": [
                    "schema"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/vnd.oai.openapi": {
                                "schema": {
                                    "type": "object",
                                    "additionalProperties": {}
                                }
                            },
                            "application/yaml": {
                                "schema": {
                                    "type": "object",
                                    "additionalProperties": {}
                                }
                            },
                            "application/vnd.oai.openapi+json": {
                                "schema": {
                                    "type": "object",
                                    "additionalProperties": {}
                                }
                            },
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "additionalProperties": {}
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/api/users/": {
            "get": {
                "operationId": "Get_Users",
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/User"
                                    }
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": [
                                            {
                                                "id": 1,
                                                "first_name": "Robert",
                                                "last_name": "Oliver",
                                                "username": "lyang",
                                                "mobile": "(482)598-4678",
                                                "email": "breanna03@example.com"
                                            }
                                        ],
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "post": {
                "operationId": "Create_User",
                "tags": [
                    "users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserRequest"
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/UserRequest"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/UserRequest"
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "first_name": "Robert",
                                            "last_name": "Oliver",
                                            "username": "lyang",
                                            "mobile": "(482)598-4678",
                                            "email": "breanna03@example.com"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        },
        "/api/users/{id}/": {
            "get": {
                "operationId": "Get_User",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this user.",
                        "required": true
                    }
                ],
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/User"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "first_name": "Robert",
                                            "last_name": "Oliver",
                                            "username": "lyang",
                                            "mobile": "(482)598-4678",
                                            "email": "breanna03@example.com"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "put": {
                "operationId": "Update_User",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this user.",
                        "required": true
                    }
                ],
                "tags": [
                    "users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UserUpdateRequest"
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/UserUpdateRequest"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/UserUpdateRequest"
                            }
                        }
                    },
                    "required": true
                },
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserUpdate"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "first_name": "Robert",
                                            "last_name": "Oliver",
                                            "username": "lyang",
                                            "mobile": "(482)598-4678",
                                            "email": "breanna03@example.com"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "patch": {
                "operationId": "Partial_Update_User",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this user.",
                        "required": true
                    }
                ],
                "tags": [
                    "users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchedUserUpdateRequest"
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchedUserUpdateRequest"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/PatchedUserUpdateRequest"
                            }
                        }
                    }
                },
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserUpdate"
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": {
                                            "id": 1,
                                            "first_name": "Robert",
                                            "last_name": "Oliver",
                                            "username": "lyang",
                                            "mobile": "(482)598-4678",
                                            "email": "breanna03@example.com"
                                        },
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            "delete": {
                "operationId": "Delete_User",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this user.",
                        "required": true
                    }
                ],
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No response body"
                    }
                }
            }
        },
        "/api/users/{id}/blogs/": {
            "get": {
                "operationId": "Get_User_Blogs",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "description": "A unique integer value identifying this user.",
                        "required": true
                    }
                ],
                "tags": [
                    "users"
                ],
                "security": [
                    {
                        "basicAuth": []
                    },
                    {
                        "tokenAuth": []
                    },
                    {
                        "TokenAuth": {
                            "type": "apiKey",
                            "in": "header",
                            "name": "Authorization",
                            "description": "Enter your token in the format \"Token <token>\""
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Blog"
                                    }
                                },
                                "examples": {
                                    "ExampleResponse": {
                                        "value": [
                                            {
                                                "id": 1,
                                                "user": 1,
                                                "title": "Doloremque et et.",
                                                "content": "Discuss than some debate this. Entire him certain single west rock......",
                                                "created_at": "2021-06-11"
                                            }
                                        ],
                                        "summary": "Detailed example"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Blog": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "readOnly": true
                    },
                    "title": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "content": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date",
                        "readOnly": true
                    },
                    "user": {
                        "type": "integer"
                    }
                },
                "required": [
                    "content",
                    "created_at",
                    "id",
                    "title",
                    "user"
                ]
            },
            "BlogRequest": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "content": {
                        "type": "string",
                        "minLength": 1
                    },
                    "user": {
                        "type": "integer"
                    }
                },
                "required": [
                    "content",
                    "title",
                    "user"
                ]
            },
            "DbEnum": {
                "enum": [
                    "ok",
                    "unavailable"
                ],
                "type": "string",
                "description": "* `ok` - ok\n* `unavailable` - unavailable"
            },
            "Health": {
                "type": "object",
                "properties": {
                    "status": {
                        "$ref": "#/components/schemas/StatusEnum"
                    },
                    "db": {
                        "$ref": "#/components/schemas/DbEnum"
                    }
                },
                "required": [
                    "status"
                ]
            },
            "PatchedBlogRequest": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "content": {
                        "type": "string",
                        "minLength": 1
                    },
                    "user": {
                        "type": "integer"
                    }
                }
            },
            "PatchedUserUpdateRequest": {
                "type": "object",
                "properties": {
                    "first_name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "last_name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "username": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "mobile": {
                        "type": "string",
                        "nullable": true,
                        "maxLength": 20
                    },
                    "password": {
                        "type": "string",
                        "writeOnly": true,
                        "minLength": 6,
                        "maxLength": 256
                    },
                    "email": {
                        "type": "string",
                        "format": "email",
                        "minLength": 1,
                        "maxLength": 254
                    }
                }
            },
            "StatusEnum": {
                "enum": [
                    "ok",
                    "error"
                ],
                "type": "string",
                "description": "* `ok` - ok\n* `error` - error"
            },
            "User": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "readOnly": true
                    },
                    "first_name": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "last_name": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "username": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "mobile": {
                        "type": "string",
                        "nullable": true,
                        "maxLength": 20
                    },
                    "email": {
                        "type": "string",
                        "format": "email",
                        "maxLength": 254
                    },
                    "register_at": {
                        "type": "string",
                        "format": "date",
                        "readOnly": true
                    }
                },
                "required": [
                    "email",
                    "first_name",
                    "id",
                    "last_name",
                    "register_at",
                    "username"
                ]
            },
            "UserRequest": {
                "type": "object",
                "properties": {
                    "first_name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "last_name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "username": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "mobile": {
                        "type": "string",
                        "nullable": true,
                        "maxLength": 20
                    },
                    "password": {
                        "type": "string",
                        "writeOnly": true,
                        "minLength": 6,
                        "maxLength": 256
                    },
                    "email": {
                        "type": "string",
                        "format": "email",
                        "minLength": 1,
                        "maxLength": 254
                    }
                },
                "required": [
                    "email",
                    "first_name",
                    "last_name",
                    "password",
                    "username"
                ]
            },
            "UserUpdate": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "integer",
                        "readOnly": true
                    },
                    "first_name": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "last_name": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "username": {
                        "type": "string",
                        "maxLength": 200
                    },
                    "mobile": {
                        "type": "string",
                        "nullable": true,
                        "maxLength": 20
                    },
                    "email": {
                        "type": "string",
                        "format": "email",
                        "maxLength": 254
                    },
                    "register_at": {
                        "type": "string",
                        "format": "date",
                        "readOnly": true
                    }
                },
                "required": [
                    "email",
                    "first_name",
                    "id",
                    "last_name",
                    "register_at",
                    "username"
                ]
            },
            "UserUpdateRequest": {
                "type": "object",
                "properties": {
                    "first_name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "last_name": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "username": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 200
                    },
                    "mobile": {
                        "type": "string",
                        "nullable": true,
                        "maxLength": 20
                    },
                    "password": {
                        "type": "string",
                        "writeOnly": true,
                        "minLength": 6,
                        "maxLength": 256
                    },
                    "email": {
                        "type": "string",
                        "format": "email",
                        "minLength": 1,
                        "maxLength": 254
                    }
                },
                "required": [
                    "email",
                    "first_name",
                    "last_name",
                    "username"
                ]
            }
        },
        "securitySchemes": {
            "basicAuth": {
                "type": "http",
                "scheme": "basic"
            },
            "tokenAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": "Token-based authentication with required prefix \"Token\""
            }
        }
    }
}